services:
  plannance-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: plannance-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@plannance-postgres:5432/plannance
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - plannance-postgres
    networks:
      - plannance-net

  plannance-postgres:
    image: postgres:16-alpine
    container_name: plannance-postgres
    environment:
      POSTGRES_DB: plannance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plannance-net

volumes:
  postgres_data:

networks:
  plannance-net:
    external: true
    name: plannance-net
