// Internal DTO for repository create operations. Password must be pre-hashed.
export type UserCreate = {
  id?: string; // public identifier; generated by repository if absent
  name: string;
  email: string;
  picture: string | null;
  password: string;
};

// Public representation — sensitive and internal fields stripped.
export type UserView = {
  id: string; // public identifier (maps to uuid column)
  name: string;
  email: string;
  picture: string | null;
};

// Input for email/password registration. Password is plaintext; hashed by UserService.
export type UserRegistration = {
  name: string;
  email: string;
  picture: string | null;
  password: string;
};
